version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: quiz_db
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quiz_user -d quiz_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: ./quiz
      dockerfile: Dockerfile
    container_name: quiz_web
    env_file:
      - ./quiz/.env
    environment:
      POSTGRES_HOST: db
      
    depends_on:
      db:
        condition: service_healthy
    
    volumes:
      - ./quiz:/app
      - staticfiles:/app/staticfiles   
      - mediafiles:/app/media          
    expose:
      - "8000"   

  nginx:
    build:
      context: ./nginx
    container_name: quiz_nginx
    depends_on:
      - web
    ports:
      - "8000:80"               
    volumes:
      - staticfiles:/static     
      - mediafiles:/media       

volumes:
  pgdata:
  staticfiles:
  mediafiles:

